=== alegeo/empProfile/src/empprofile/companyInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
    xmlns:com="http://namespace.profile.com/ns/com"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://namespace.profile.com/ns/com"
    elementFormDefault="qualified"> 
        
    <xsd:element name="companyInfo">
        <xsd:complexType>
        <xsd:sequence>
        <xsd:element name="companies">
            <xsd:complexType>
                <xsd:sequence>
                        <xsd:element name="company" maxOccurs="unbounded">
                            <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="companyId" type="xsd:string"/>
                                <xsd:element name="companyName" type="xsd:string"/>
                                <xsd:element name="category" type="xsd:string"/>
                                <xsd:element name="founders" type="xsd:string"/>
                                <xsd:element name="ceo" type="xsd:string"/>
                                <xsd:element name="location" type="xsd:string"/>
                                <xsd:element name="contact" type="xsd:string"/>
                            </xsd:sequence> 
                          </xsd:complexType>
                        </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
        </xsd:sequence>
        </xsd:complexType>
    </xsd:element>           
</xsd:schema>

=== alegeo/empProfile/zgzf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<ns1:companyInfo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://namespace.profile.com/companyInfo/com'
    xsi:schemaLocation='http://namespace.profile.com/companyInfo/com src/empprofile/companyInfo.xsd'>
    <company>
        <companyName></companyName>
        <category></category>
        <founders></founders>
        <ceo></ceo>
        <location></location>
        <contact></contact>
    </company>

</ns1:companyInfo>
