=== alegeo/empProfile/src/empprofile/profile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:app="http://namespace.profile.com/ns/profile"
	targetNamespace="http://namespace.profile.com/ns/profile"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"	
        xmlns:e="http://namespace.profile.com/ns/empRecord"
	xmlns:cv="http://namespace.profile.com/ns/cv"
	xmlns:com="http://namespace.profile.com/ns/companyInfo"
	xmlns:t="http://namespace.profile.com/ns/transcript"
	elementFormDefault="qualified">
<!--
<xsd:import schemaLocation="empRecord.xsd"
namespace="http://namespace.profile.com/empRecord/e" />
<xsd:import schemaLocation="cv.xsd"
namespace="http://namespace.profile.com/cv" />
<xsd:import schemaLocation="companyInfo.xsd"
namespace="http://namespace.profile.com/companyInfo/com" />
<xsd:import schemaLocation="transcript.xsd"
namespace="http://namespace.profile.com/transcript/t" />
-->
    <xsd:element name="profile">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="cv_info">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="name" type="xsd:string"/>
                                <xsd:element name="address" type="xsd:string"/>
                                <xsd:element name="telephone" type="xsd:string"/>
                                <xsd:element name="email" type="xsd:string" />
                                <xsd:element name="education" type="xsd:string"/>
                                <xsd:element name="language" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>                
                                <xsd:element name="qualifications" type="xsd:string"/>
                                <xsd:element name="jobType" type="xsd:string"/>
                                <xsd:element name="desiredPosition" type="xsd:string"/> 
                                <xsd:element name="references" type="xsd:string"/>
                                <xsd:element name="motivation" type="xsd:string"/>   
                            </xsd:sequence>
                        </xsd:complexType>  
                </xsd:element> 
                
                <xsd:element name="empRecord">
                        <xsd:complexType>
                            <xsd:sequence>
                            <xsd:element name="empName" type="xsd:string"/>
                            <xsd:element name="companyWorked" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="workedAtComId" type="xsd:string"/>
                                        <xsd:element name="workedAt" type="xsd:string"/>
                                        <xsd:element name="duration" type="xsd:string"/>
                                        <xsd:element name="year" type="xsd:int"/>
                                        <xsd:element name="position" type="xsd:string"/>                       
                                    </xsd:sequence>
                                </xsd:complexType>    
                            </xsd:element>    
                            </xsd:sequence>
                        </xsd:complexType>
                </xsd:element>   
                               
                <xsd:element name="companyInfo">
                    <xsd:complexType>
                        <xsd:sequence>
                        <xsd:element name="companies">
                            <xsd:complexType>
                                <xsd:sequence>
                                        <xsd:element name="company" minOccurs="0" maxOccurs="unbounded">
                                            <xsd:complexType>
                                            <xsd:sequence>
                                                <xsd:element name="companyId" type="xsd:string"/>
                                                <xsd:element name="companyName" type="xsd:string"/>
                                                <xsd:element name="category" type="xsd:string"/>
                                                <xsd:element name="founders" type="xsd:string"/>
                                                <xsd:element name="ceo" type="xsd:string"/>
                                                <xsd:element name="location" type="xsd:string"/>
                                                <xsd:element name="contact" type="xsd:string"/>
                                            </xsd:sequence> 
                                          </xsd:complexType>
                                        </xsd:element>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>	
                
                <xsd:element name="transcript">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="studentName" type="xsd:string"/>
                            <xsd:element name="university" type="xsd:string"/>
                            <xsd:element name="program" type="xsd:string"/>
                            <xsd:element name="issueDate" type="xsd:date"/>
                            <xsd:element name="gpa" type="xsd:decimal" minOccurs="0"/>
                            <xsd:element name="courses">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="course" minOccurs="1" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                    <xsd:sequence>
                                                            <xsd:element name="code">
                                                                    <xsd:simpleType>
                                                                    <xsd:restriction base="xsd:string">
                                                                            <xsd:pattern value="[A-Z][A-Z][0-9][0-9][0-9][0-9]"/>
                                                                    </xsd:restriction>
                                                                    </xsd:simpleType>
                                                            </xsd:element>	
                                                            <xsd:element name="title" type="xsd:string" />
                                                            <xsd:element name="credits" type="xsd:decimal" />
                                                            <xsd:element name="grade" type="xsd:string" />
                                                    </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>               
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>                                        
                                                	
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>  
</xsd:schema>

=== alegeo/empProfile/src/empprofile/prof.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<app:profile
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:app='http://namespace.profile.com/ns/profile'
    xsi:schemaLocation='http://namespace.profile.com/ns/profile profile.xsd'>
    <cv_info>
    <name>dhf</name>
    <address>hgs</address>
    <telephone>464364</telephone>
    <telephone>3464</telephone>
    <email>fsdh@sh.se</email>
    <email>fsdh@sh.se</email>
    <education>
        <university>ry</university>
        <program>sth</program>
        <gpa>3.6</gpa>
    </education>
    <language>tst</language>
    <language>sthss</language>
    <qualifications>styste</qualifications>
    <jobType>sth</jobType>
    <desiredPosition>sty</desiredPosition>
    <references>stdu</references>
    <motivation>stuw</motivation>
    </cv_info>
    <empRecord>
        <empName>twwww</empName>
        <workedAt>stwwhw</workedAt>
        <year>3245</year>
        <duration>stru</duration>
        <position>swtusw</position>
    </empRecord>
    <empRecord>
        <empName>stuwe</empName>
        <workedAt>srtuwu</workedAt>
        <year>2454</year>
        <duration>45 tht</duration>
        <position>5ywew</position>
    </empRecord>
    <companyInfo>
        <companyName>trhwrewh</companyName>
        <category>wthwh</category>
        <founders>wehyew</founders>
        <ceo>wethyeq</ceo>
        <location>weh5ye5qw</location>
        <contact>wehywe</contact>
    </companyInfo>

</app:profile>

=== alegeo/empProfile/src/empprofile/profile_validation.xml
<?xml version="1.0" encoding="UTF-8"?>
<app:profile
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:app='http://namespace.profile.com/profile'
    xsi:schemaLocation='http://namespace.profile.com/profile profile.xsd'>
    <app:cv_info>
        <app:name></app:name>
        <app:address></app:address>
        <app:telephone></app:telephone>
        <app:email></app:email>
        <app:education></app:education>
        <app:language></app:language>
        <app:qualifications></app:qualifications>
        <app:jobType></app:jobType>
        <app:desiredPosition></app:desiredPosition>
        <app:references></app:references>
        <app:motivation></app:motivation>
    </app:cv_info>
    <app:empRecord>
        <app:empName></app:empName>
        <app:companyWorked>
            <app:workedAtComId></app:workedAtComId>
            <app:workedAt></app:workedAt>
            <app:duration></app:duration>
            <app:year></app:year>
            <app:position></app:position>
        </app:companyWorked>
    </app:empRecord>
    <app:companyInfo>
        <app:companies>
            <app:company>
                <app:companyId></app:companyId>
                <app:companyName></app:companyName>
                <app:category></app:category>
                <app:founders></app:founders>
                <app:ceo></app:ceo>
                <app:location></app:location>
                <app:contact></app:contact>
            </app:company>
        </app:companies>
    </app:companyInfo>
    <app:transcript>
        <app:studentName></app:studentName>
        <app:university></app:university>
        <app:program></app:program>
        <app:issueDate></app:issueDate>
        <app:gpa></app:gpa>
        <app:courses>
            <app:course>
                <app:code></app:code>
                <app:title></app:title>
                <app:credits></app:credits>
                <app:grade></app:grade>
            </app:course>
            <app:course>
                <app:code></app:code>
                <app:title></app:title>
                <app:credits></app:credits>
                <app:grade></app:grade>
            </app:course>
            <app:course>
                <app:code></app:code>
                <app:title></app:title>
                <app:credits></app:credits>
                <app:grade></app:grade>
            </app:course>
            <app:course>
                <app:code></app:code>
                <app:title></app:title>
                <app:credits></app:credits>
                <app:grade></app:grade>
            </app:course>
        </app:courses>
    </app:transcript>

</app:profile>

=== alegeo/empProfile/src/jaxb_output.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><profile xmlns="http://namespace.profile.com/ns/profile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://namespace.profile.com/ns/profile profile.xsd"><cv_info><name>Annabelle White</name><address>Kungshamra 5</address><telephone>+34-123321-5312</telephone><email>annaw@kth.se</email><education>Master Software Engineering of Distributed Systems</education><language>English</language><language>Swedish</language><qualifications>Driving license (car)</qualifications><jobType>Permanent</jobType><desiredPosition>Software Developer</desiredPosition><references>Available upon request</references><motivation>I am suitable for the position of a software developer because</motivation></cv_info><empRecord><empName>Annabelle White</empName></empRecord><companyInfo><companies/></companyInfo><transcript><studentName>Annabelle White</studentName><university>KTH</university><program>Masters Software Engineering of Distributed Systems</program><issueDate>2012-12-23</issueDate><courses><course><code>IK2210</code><title>Distributed Systems, Basic Course</title><credits>7.5</credits><grade>A</grade></course><course><code>IB2210</code><title>Modern Methods in Software Engineering</title><credits>7.5</credits><grade>B</grade></course><course><code>IB2250</code><title>Distributed Artificial Intelligence and Intelligent Agents</title><credits>7.5</credits><grade>A</grade></course></courses></transcript></profile>

=== alegeo/empProfile/src/empprofile/profile_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<ns1:profile
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://namespace.profile.com/profile'
    xsi:schemaLocation='http://namespace.profile.com/profile profile.xsd'>
    <cv_info>
        <name></name>
        <address></address>
        <telephone></telephone>
 
        <email></email>
        <education>
            <university></university>
            <program></program>
            <gpa></gpa>
        </education>
        <language></language>
        <language></language>
        <language></language>
        <qualifications></qualifications>
        <jobType></jobType>
        <desiredPosition></desiredPosition>
        <references></references>
        <motivation></motivation>
    </cv_info>
    <empRecord>
        <name></name>
        <category></category>
        <contact></contact>
        <year></year>
        <duration></duration>
        <position></position>
    </empRecord>
    <empRecord>
        <name></name>
        <category></category>
        <contact></contact>
        <year></year>
        <duration></duration>
        <position></position>
    </empRecord>
    <empRecord>
        <name></name>
        <category></category>
        <contact></contact>
        <year></year>
        <duration></duration>
        <position></position>
    </empRecord>
    <companyInfo>
        <company_name></company_name>
        <category></category>
        <founders></founders>
        <ceo></ceo>
        <location></location>
        <contact></contact>
    </companyInfo>

</ns1:profile>

=== alegeo/empProfile/src/empprofile/xslt_output.xml
<?xml version="1.0" encoding="UTF-8"?>
<app:profile xsi:schemaLocation="http://namespace.profile.com/ns/profile profile.xsd" xmlns:apcv="http://namespace.profile.com/ns/cv" xmlns:com="http://namespace.profile.com/ns/com" xmlns:t="http://namespace.profile.com/ns/transcript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:e="http://namespace.profile.com/ns/empRecord" xmlns:app="http://namespace.profile.com/ns/profile">
    <app:cv_info>
        <app:name>Annabelle White</app:name>
        <app:address>Kungshamra 5</app:address>
        <app:telephone>+34-123321-5312</app:telephone>
        <app:email>annaw@kth.se</app:email>
        <app:education>Master Software Engineering of Distributed Systems</app:education>
        <app:language>English</app:language>
        <app:language>Swedish</app:language>
        <app:qualifications>Driving license (car)</app:qualifications>
        <app:jobType>Permanent</app:jobType>
        <app:desiredPosition>Software Developer</app:desiredPosition>
        <app:references>Available upon request</app:references>
        <app:motivation>I am suitable for the position of a software developer because</app:motivation>
    </app:cv_info>
    <app:empRecord>
        <app:empName>Annabelle White</app:empName>
        <app:companyWorked>
            <app:workedAtComId>1</app:workedAtComId>
            <app:workedAt>Nokia</app:workedAt>
            <app:duration>18 months</app:duration>
            <app:year>2011</app:year>
            <app:position>Software Developer</app:position>
        </app:companyWorked>
    </app:empRecord>
    <app:companyInfo>
        <app:companies>
            <app:company>
                <app:companyId>1</app:companyId>
                <app:companyName>Nokia</app:companyName>
                <app:category>Telecommunications</app:category>
                <app:founders>Fredrik Idestam, Leo Mechelin</app:founders>
                <app:ceo>Stephen Elop</app:ceo>
                <app:location>Espoo, Finland</app:location>
                <app:contact>56-806-836-1357</app:contact>
            </app:company>
        </app:companies>
    </app:companyInfo>
    <app:transcript>
        <app:studentName>Annabelle White</app:studentName>
        <app:university>KTH</app:university>
        <app:program>Masters Software Engineering of Distributed Systems</app:program>
        <app:issueDate>2012-12-23</app:issueDate>
        <app:gpa>3.526</app:gpa>
        <app:courses>
            <app:course>
                <app:code>IK2210</app:code>
                <app:title>Distributed Systems, Basic Course</app:title>
                <app:credits>7.5</app:credits>
                <app:grade>A</app:grade>
            </app:course>
            <app:course>
                <app:code>IB2210</app:code>
                <app:title>Modern Methods in Software Engineering</app:title>
                <app:credits>7.5</app:credits>
                <app:grade>B</app:grade>
            </app:course>
            <app:course>
                <app:code>IB2210</app:code>
                <app:title>Distributed Artificial Intelligence and Intelligent Agents</app:title>
                <app:credits>7.5</app:credits>
                <app:grade>A</app:grade>
            </app:course>
            <app:course>
                <app:code>ID1234</app:code>
                <app:title>Network Programming in Java</app:title>
                <app:credits>6</app:credits>
                <app:grade>B</app:grade>
            </app:course>
        </app:courses>
    </app:transcript>
</app:profile>
