=== alegeo/empProfile/src/empprofile/transcript.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
    xmlns:t="http://namespace.profile.com/ns/transcript"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://namespace.profile.com/ns/transcript"
    elementFormDefault="qualified">
    
    <xsd:element name="transcript">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="studentName" type="xsd:string"/>
		<xsd:element name="university" type="xsd:string"/>
                <xsd:element name="program" type="xsd:string"/>
                <xsd:element name="issueDate" type="xsd:date"/>
                <xsd:element name="courses">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="course" minOccurs="1" maxOccurs="unbounded">
                                <xsd:complexType>
                                        <xsd:sequence>
                                                <xsd:element name="code">
                                                        <xsd:simpleType>
                                                        <xsd:restriction base="xsd:string">
                                                                <xsd:pattern value="[A-Z][A-Z][0-9][0-9][0-9][0-9]"/>
                                                        </xsd:restriction>
                                                        </xsd:simpleType>
                                                </xsd:element>	
                                                <xsd:element name="title" type="xsd:string" />
                                                <xsd:element name="credits" type="xsd:decimal" />
                                                <xsd:element name="grade" type="xsd:string" />
                                        </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>               
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
</xsd:schema>

=== alegeo/empProfile/src/transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<transcript
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='transcript.xsd'>
    <name>Alexandra Georgoudaki</name>
    <university>KTH</university>
    <program>Master Software Engineering of Distributed Systems</program>
    <issue-date>2012-12-23</issue-date>
    <courses>
        <course>
            <code>IK2210</code>
            <title>Distributed Systems, Basic Course</title>          
            <credits>7.5</credits>
            <grade>A</grade>
        </course>
        <course>
            <code>IB2210</code>
            <title>Modern Methods in Software Engineering</title>
            <credits>7.5</credits>
            <grade>A</grade>
        </course>
        <course>
            <code>IB2210</code>
            <title>Distributed Artificial Intelligence and Intelligent Agents</title>
            <credits>7.5</credits>
            <grade>A</grade>
        </course>
        <course>
            <code>ID1234</code>
            <title>Network Programming in Java</title>
            <credits>6</credits>
            <grade>B</grade>
        </course>
    </courses>

</transcript>

=== alegeo/empProfile/src/empprofile/transcrip.xml
<?xml version="1.0" encoding="UTF-8"?>
<t:transcript
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:t='http://namespace.profile.com/ns/transcript'
    xsi:schemaLocation='http://namespace.profile.com/ns/transcript transcript.xsd'>
    <t:studentName>s</t:studentName>
    <t:courses>
        <t:course>
            <t:code></t:code>
            <t:title></t:title>
            <t:credits></t:credits>
            <t:grade></t:grade>
        </t:course>
        <t:course>
            <t:code></t:code>
            <t:title></t:title>
            <t:credits></t:credits>
            <t:grade></t:grade>
        </t:course>
        <t:course>
            <t:code></t:code>
            <t:title></t:title>
            <t:credits></t:credits>
            <t:grade></t:grade>
        </t:course>
        <t:course>
            <t:code></t:code>
            <t:title></t:title>
            <t:credits></t:credits>
            <t:grade></t:grade>
        </t:course>
    </t:courses>

</t:transcript>

=== alegeo/empProfile/src/empprofile/transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<t:transcript
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:t='http://namespace.profile.com/ns/transcript'
    xsi:schemaLocation='http://namespace.profile.com/ns/transcript transcript.xsd'>
    <t:studentName>Annabelle White</t:studentName>
    <t:university>KTH</t:university>
    <t:program>Masters Software Engineering of Distributed Systems</t:program>
    <t:issueDate>2012-12-23</t:issueDate>
    <t:courses>
        <t:course>
            <t:code>IK2210</t:code>
            <t:title>Distributed Systems, Basic Course</t:title>
            <t:credits>7.5</t:credits>
            <t:grade>A</t:grade>
        </t:course>
        <t:course>
            <t:code>IB2210</t:code>
            <t:title>Modern Methods in Software Engineering</t:title>
            <t:credits>7.5</t:credits>
            <t:grade>B</t:grade>
        </t:course>
        <t:course>
            <t:code>IB2210</t:code>
            <t:title>Distributed Artificial Intelligence and Intelligent Agents</t:title>
            <t:credits>7.5</t:credits>
            <t:grade>A</t:grade>
        </t:course>
        <t:course>
            <t:code>ID1234</t:code>
            <t:title>Network Programming in Java</t:title>
            <t:credits>6</t:credits>
            <t:grade>B</t:grade>
        </t:course>
    </t:courses>

</t:transcript>
